### ISSUE TITLE
Lokálne rozbehanie LIST-u

### ISSUE THREAD

**Issue by pitak4** [TIS2022-FMFI/list-formulas#2]

**Comment by PavolRepisky** [comment]
**Windows:**

1. Nainštalovať [Docker desktop](https://docs.docker.com/desktop/install/windows-install/) a [WSL].(https://learn.microsoft.com/en-us/windows/wsl/install).
2. V nastaveniach **_Docker desktop_** povoliť integráciu s _**WSL**_.
3. Do súboru 
     > ...\Windows\System32\drivers\etc\hosts
    
    pridať riadok `127.0.0.1	server.listdev`.
4. Vyklonovať GitHub projekt do _**WSL**_ file systému.
5. V koreňovom adresári projektu zavolať príkaz `docker-compose up -d`.
6. Zavolať príkaz `docker-compose exec list-server bash`  a následne spustiť súbor **_initDependencies_** príkazom `sudo ./initDependencies`.
7. Spustiť príkaz `bin/console update_database`.
8. Vytvoriť nového učiteľa pre prístup do systému príkazom `bin/console new_teacher`.
9. Server by teraz mal bežať na adrese [http://server.listdev/admin](http://server.listdev/admin), kde je možné sa prihlásiť pomocou údajov zadaných pri vytváraní nové učiteľa v predchádzajúcom kroku.


**Linux:**

1. Nainštalovať [Docker Engine](https://docs.docker.com/engine/install/ubuntu/).
2. Do súboru 
     > \etc\hosts
    
    pridať riadok `127.0.0.1	server.listdev`.
4. Vyklonovať GitHub projekt .
5. V koreňovom adresári projektu zavolať príkaz `docker-compose up -d`.
6. Zavolať príkaz `docker-compose exec list-server bash`  a následne spustiť súbor **_initDependencies_** príkazom `sudo ./initDependencies`.
7. Spustiť príkaz `bin/console update_database`.
8. Vytvoriť nového učiteľa pre prístup do systému príkazom `bin/console new_teacher`.
9. Server by teraz mal bežať na adrese [http://server.listdev/admin](http://server.listdev/admin), kde je možné sa prihlásiť pomocou údajov zadaných pri vytváraní nové učiteľa v predchádzajúcom kroku.
