### ISSUE TITLE
Kontrola finalnej verzie Katalogu Poziadaviek

### ISSUE THREAD

**Issue by pitak4** [TIS2022-FMFI/list-formulas#21]
https://docs.google.com/document/d/1UCqyoc-yavRoxD4R-87v5GEMat5MFa5tlhQDlXTqkNU/view

**Comment by pavelpetrovic** [comment]
zatial sem pastujem, co som napisal na stretnuti do notepadu:

virtualny typ zostavy "úlohy z programovacieho jazyka C": 

studentovi by sa malo ukazovat
cislo - percento do celkovej znamky

15 * (Cvičenie na hodine + Domáca úloha + Prémia c) /
(max. Cvičenie na hodine + max. Domáca úloha + max. Prémia c)

priklad studentskeho vystupu pre tento virtualny typ zostav:

úlohy z programovacieho jazyka C
77.5 / 70.5 (15%)

nova myslienka:  pridat jeden optional koeficient aj do 
realneho typu zostav, aby sa studentovi aj ucitelovi zobrazovalo
vysledny pocet bodov, resp. percent do celkoveho suctu

**Comment by pavelpetrovic** [comment]
preštudoval som si aktuálnu verziu KP. 
upresnil som niektoré formulácie a pridal jeden komentár.
všetko v režime "suggesting", takže to skontrolujte a akceptujte alebo upravte ako potrebujete. potom, prosím, pošlite KP svojmu zadavateľovi, aby si ho dôkladne preštudoval a dal Vám vedieť, čo v ňom podľa neho treba upraviť, doplniť a pod.
ďakujem.
