### ISSUE TITLE
Build Kempelen DB

### ISSUE THREAD

**Issue by pitak4** [TIS2022-FMFI/list-formulas#23]
Mame online DB pripravenu pre nas team. Je potrebne inicializovat vsetky tabulky aby bol identicky s LIST-om

**Comment by AnonyMnaUmouS** [comment]
vytvorene mysql databaza:
user: timotea
pwd: gastanko123
host: kempelen.dai.fmph.uniba.sk
malo by fungovat:
https://kempelen.dai.fmph.uniba.sk/phpmyadmin
