### ISSUE TITLE
[Návrh] Research alternatív wkhtmltopdf

### ISSUE THREAD

**Issue by pitak4** [TIS2022-FMFI/list-formulas#50]
Najst alternativne aplikacie pre export formou HTML->PDF. Zapisat ako funguje app a ako sa lisi (rychly, zabera vela pamate,...)

Na next team meeting sa pozrieme a vyberieme presne app, ktory pouzijeme.

**Comment by AnonyMnaUmouS** [comment]
WkHtmlToPdf
Puppeteer
WeasyPrint
//PhantomJS

https://wkhtmltopdf.org/
Wkhtmltopdf is an open-source command-line tool you can use to turn HTML into PDF using the 
QtWebKit rendering engine. 

https://pptr.dev/
Puppeteer is a Node.js library which provides a high-level API to control Chrome/Chromium over 
the DevTools Protocol. 

Puppeteer
+ Easier to use
+ ~ 3x rýchlejší ako WkHtmlToPdf
- veľkosť vygenerovaných súborov je 5-10 násobne väčšia
- Podporuje iba Google Chrome a Chromiom-based prehliadače (napr. Brave, Opera, Edge) (v2.1.0 firefox)

https://weasyprint.org/
WeasyPrint

- ~ 2x pomalší ako WkHtmlToPdf

/*
https://phantomjs.org/
PhantomJS
*/
