### ISSUE TITLE
Spoznat List UI

### ISSUE THREAD

**Issue by pitak4** [TIS2022-FMFI/list-formulas#7]
Urobit si zakladnu orientaciu LIST UI, vediet ktore okno/cast okna je ktora cast kodu.

**Comment by pavelpetrovic** [comment]
z dnesneho stretnutia:

vsetci su pritomni
--
zapisnica je, trosku strucna, ale prosim vzdy urcit za co je kto zodpovedny v dalsom obdobi
mame databazu so strukturou ako ma aktualny list, akurat v nej nie su ziadne data, treba vyskusat, ci s tym list funguje a da sa tam:
- vytvorit obdobie
- vytvorit kurz
- vytvorit typy zostav
- pridat typy zostav do kurzu
- nastavit skupiny a ich miestnosti kurzu (z toho vyplyva kapacita kurzu)
- studenti - sprava studentov: pridat studentske ucty
- studenti - ucastnici kurzov - pridat studentov do kurzu
- ulohy - vytvorit nove ulohy
- zostavy - vytvorit nove zostavy s uz vytvorenymi ulohami (vzdy najskor otvorit zostavu a potom v zozname uloh tlacidlo "vybrat" (ikonka))
- submit od studenta
- hodnotit: studenti - riesenia zostav uloh
- pridate body
- zobrazite si tabulku - tabulky hodnoteni
issues funguju pekne, je tam potencial na zlepsenie (napr. mi chyba cely navrh zmien v UI)
